<?php

namespace AppBundle\Repository;

/**
 * agenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class agenceRepository extends \Doctrine\ORM\EntityRepository
{
}
