<?php

namespace AppBundle\Repository;

/**
 * rdv_planifieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rdv_planifieRepository extends \Doctrine\ORM\EntityRepository
{
}
